### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Jakousa** [OliverMartikainen/pub_QueueMonitor#1]
# Katselmointi

### Mitä tein

* 20.12.2019 klo ~16:30

* En löytänyt linkkiä projektiin?
  * https://github.com/fullstackopen-2019/misc/blob/master/projekti.md

```
  GitHub-repositoriosi README.md-tiedostossa tulee olla linkki osoitteeseen, missä sovellus on käynnissä. Jos teet mobiilisovelluksen, sovitaan sovelluksen demoamisesta tapauskohtaisesti.
```

## Koodi

* Oli frontissa hyvä idea kansioida osa komponenteista. 

* Sen sijaan että tekisit if voit käyttää oletusparametreja: https://github.com/OliverMartikainen/pub_QueueMonitor_Frontend/blob/0b74a451205c2964c641cd7ba4fa73e1e4dbc60a/src/components/QueueSection.js#L27 katso esim https://wesbos.com/destructuring-default-values/

* App.js https://github.com/OliverMartikainen/pub_QueueMonitor_Frontend/blob/0b74a451205c2964c641cd7ba4fa73e1e4dbc60a/src/App.js on aika pitkä. Voisikohan sen jakaa useampaan pienempään osaan?
  * Samassa tiedostossa on aika paljon käytetty kommentteja poistamaan koodia. Koodin versionhallintaan git on yleisesti parempi työkalu.

* Voit käyttää ympäristömuuttujia ympäristöstä riippuvaa koodin suoritusta kommenttien sijaan https://github.com/OliverMartikainen/pub_QueueMonitor_Frontend/blob/0b74a451205c2964c641cd7ba4fa73e1e4dbc60a/src/utils/config.js

* app.js https://github.com/OliverMartikainen/pub_QueueMonitor/blob/3ec1c63c2d22a5b8b781ce549c97f2cd9b288afb/app.js on myös aika pitkä ja tekee montaa asiaa. Voisikohan senkin jakaa useampaan osaan?

* pushRouterissa on virheenkäsittely hieman huolestuttava, eihän ne katoa asyncin takia? Katso https://www.npmjs.com/package/express-async-errors ja https://codeburst.io/node-express-async-code-and-error-handling-121b1f0e44ba

## Kokonaisuus

* Kaikenkaikkiaan hyvä lopputulos, tästä on hyvä jatkaa!

* Mielenkiintoiselta vaikuttava projekti

**Comment by OliverMartikainen** [comment]
Lisäsin README tiedostoon linkin projektiin: https://queuemonitor.herokuapp.com/
